-- Supabase schema for NutriFit
-- Corrected Supabase schema for NutriFit that matches the backend code

create table if not exists public.meals (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    calories int,
    timestamp timestamp with time zone default timezone('utc', now()) default now()
);

create table if not exists public.activities (
    id bigint generated by default as identity primary key,
    activity text not null,
    duration int,
    calories_burned int,
    timestamp timestamp with time zone default timezone('utc', now()) default now()
);

-- User profiles table to store additional user information
create table if not exists public.user_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text,
    weight_kg float,
    height_cm float,
    age int,
    gender text check (gender in ('male', 'female', 'other', 'prefer_not_to_say')),
    bmi float,
    fitness_goal text,
    created_at timestamp with time zone default timezone('utc', now()),
    updated_at timestamp with time zone default timezone('utc', now())
);

-- Enable Row Level Security
alter table public.user_profiles enable row level security;

-- Create policies for user_profiles
create policy "Users can view their own profile"
    on public.user_profiles for select
    using (auth.uid() = id);

create policy "Users can insert their own profile"
    on public.user_profiles for insert
    with check (auth.uid() = id);

create policy "Users can update their own profile"
    on public.user_profiles for update
    using (auth.uid() = id);